load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#############################################################################################
# Toolchain: arm-none-eabi-gcc v1.2.0.
http_archive(
    name = "arm_none_eabi",
    sha256 = "34487973fd09f655a0b4531fb48cec5795bec303de30223aef43606b01fcb161",
    strip_prefix = "bazel-arm-none-eabi-1.2.0",
    url = "https://github.com/d-asnaghi/bazel-arm-none-eabi/archive/v1.2.0.tar.gz",
)

load("@arm_none_eabi//:deps.bzl", "arm_none_eabi_deps")

arm_none_eabi_deps()
#############################################################################################

#############################################################################################
# Rust embedded tools
local_repository(
    name = "rust_embedded",
    path = "..",
)

load("@rust_embedded//:repositories.bzl", "rust_embedded_repositories")

rust_embedded_repositories()

load("@rust_embedded//:deps.bzl", "rust_embedded_deps")

rust_embedded_deps()
#############################################################################################
